version: "3.9"

services:
  app:
    container_name: internet_lab_app
    build:
      context: .
    image: goodwin954/internet_lab
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
     - my_network
  redis:
    container_name: internet_lab_redis
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network
  mysql:
    container_name: internet_lab_mysql
    image: mysql:latest
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: internet_lab
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
     - "3306:3306"
    volumes:
     - ./mysql_data:/var/lib/mysql
     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h mysql -u user -p$MYSQL_PASSWORD" ]
      interval: 5s
      timeout: 15s
      retries: 20
    networks:
     - my_network
networks:
  my_network:
    driver: bridge
